---
title: "MCH_grapher"
author: "KeachMurakami"
date: "August 13, 2015"
output: html_document
---

---
output:
  html_document:
    css: /Users/keach/Dropbox/R/Sources/markdown.css
---

making graphs (temp RH, and CO2conc.) from MCH-383SD
========================================================
```{r eval = TRUE}
opts_chunk$set(eval = TRUE,
               error = FALSE,
               prompt = TRUE,
               message = FALSE,
               fig.hight = 20,
               fig.width = 12,
               warning = FALSE)

library(DT)
library(tidyr)
library(data.table)
```

```{r input, echo = FALSE}
home.dir()
setwd(dir = "~/GitHub/BeeLabR/environmental/MCH_grapher/")

Memo.file <-
  dir(pattern = "xlsx")
Memo.dat <- 
  Memo.file %>%
  read.xlsx(sheetIndex = 1, stringsAsFactors = FALSE)

if(length(Memo.file) != 1) print("no memo file found")
  
Plant <- Memo.dat[2, 2]
Room <- Memo.dat[3, 2]
Memo <- Memo.dat[4, 2]

StartDay <- Memo.dat[5, 2] %>% as.numeric
StartTime <- Memo.dat[6, 2] %>% as.numeric
EndDay <- Memo.dat[7, 2] %>% as.numeric
EndTime <- Memo.dat[8, 2] %>% as.numeric

Memo.dat1 <-
  Memo.dat %>%
  select(-(1:2)) %>%
  filter(is.used. > 0)

MCH.names <- Memo.dat1$MCH.id
MCH.num <- length(MCH.names)
chamID <- Memo.dat1$Where.
LightSources <- Memo.dat1$LightSources
Remarks <- Memo.dat1$Remarks

type.num <- 3

types <- c("temp", "RH", "CO2")

# Memo.dat2 <-
#   Memo.dat1 %>%
#   mutate(Names = paste0(Where., ":", What.)) %>%
#   select(-is.used., -Where., -What., -LightSources, -Remarks)

# read in the data from each MCH
data <-
  lapply(1:MCH.num, function(i){
      
    DataDirs <-
      dir(paste0("../RawData/MCH_logs/No", MCH.names[i], "/"))
    
    DataDirsUsed <-
      DataDirs[(as.numeric(DataDirs) > StartDay) & (as.numeric(DataDirs) <= EndDay)]
    
    DataFiles <-
      dir(paste0("../RawData/MCH_logs/No", MCH.names[i], "/", DataDirsUsed, "/"), full.names = TRUE)
    
    if(length(DataFiles) == 0) print("no CSV files detected")
    
    calb <-
      read.csv("../calibration/MCH.csv") %>%
      filter(MCH_no == as.numeric(MCH.names)[i])
    
    lapply(1:length(DataFiles), function(x){
        fread(input = DataFiles[x], header = TRUE) %>%
        select(Date, Time, RH = 4, temp = 6, CO2 = 8) %>%
        mutate(RH = RH * calb$hum_a + calb$hum_b,
               temp = temp * calb$temp_a + calb$temp_b,
               CO2 = CO2 * calb$CO2_a + calb$CO2_b) %>%
        return
      }) %>%
      rbind_all %>%
      mutate(MCHid = MCH.names[i],
             chamID = chamID[i],
             LightOn = Memo.dat1$LightOn[i],
             LightOff = Memo.dat1$LightOff[i]) %>%
      return
    }) %>%
  rbind_all
```

Information
-----------
* calculated at `r Sys.time()`  

```{r data_handling}
DNdet <- function(Hour, ONtime, OFFtime){
  Hour <- as.numeric(Hour)
    ifelse(test = (Hour >= ONtime && Hour < OFFtime) , yes = "Day", no = "Night")
}


Date_used <-
  data$Date %>%
  stringr::str_replace_all("/", "")
Time_used <-
  data$Time %>%
  stringr::str_replace_all(":", "")
UsedData <-
  as.numeric(paste0(Date_used, Time_used))

Starts <-
  as.numeric(paste0(StartDay, StartTime))
Ends <-
  as.numeric(paste0(EndDay, EndTime))

Used <- ((UsedData > Starts) & (UsedData < Ends))


data1 <-
  data[Used,] %>%
  separate(col = Time, into = c("Hour", "Min", "Sec"), sep = ":", remove = F) %>%
  mutate(DayNight = Vectorize(DNdet)(Hour, LightOn, LightOff))


daily_summary <-
  data1 %>%
  select(Date, DayNight, RH:CO2, chamID) %>%
  melt(id.vars = c("Date", "DayNight", "chamID")) %>%
  group_by(Date, DayNight, chamID, variable) %>%
  summarise_each(funs(mean2, sd2)) %>%
  mutate(ave = sprintf("%.1f", mean2),
         sd = sprintf("%.2f", sd2),
         ave.sd = paste0(ave, "+-", sd, "SD")) %>%
  select(Date, DayNight, chamID, variable, ave, sd, ave.sd)

span_summary <-
  data1 %>%
  select(DayNight, RH:CO2, chamID) %>%
  melt(id.vars = c("DayNight", "chamID")) %>%
  group_by(DayNight, chamID, variable) %>%
  summarise_each(funs(mean2, sd2)) %>%
  mutate(ave = sprintf("%.1f", mean2),
         sd = sprintf("%.2f", sd2),
         ave.sd = paste0(ave, "+-", sd, "SD")) %>%
  select(DayNight, variable, ave, sd, ave.sd)
```


```{r Graphics}
    data2 <-
        data1 %>%
        mutate(Time = as.POSIXct(strptime(paste0(Date, ":", Time), format = "%Y/%m/%d:%H:%M:%S"))) %>%
    select(Time, DayNight, chamID, MCHid, RH:CO2) %>%
    melt(id.vars = c("Time", "DayNight", "chamID", "MCHid")) %>%
    data.table

Graphics <-
  lapply(1:type.num, function(x){
    data3 <-
      data2 %>%
      filter(variable == types[x])
    
      hists <- 
        data3 %>%
        ggplot(data = ., aes(x = value, y = ..density.., fill = DayNight)) +
        theme_bw(20) +
        geom_histogram(color = "grey", fill = "cornsilk", alpha = 1) +
        geom_density(color = "grey", alpha = 0.3) +
        xlab(NULL) +
        facet_grid(chamID ~ .)
    
      timecourse <-
        data3 %>%
        ggplot(aes(x = Time, y = value, color = DayNight)) +
        theme_bw(20) +
        geom_line(color = "grey") +
        geom_point(alpha = 1, size = 1) +
        facet_grid(chamID ~ .)
      
      list(Histgram = hists, TimeCourse = timecourse) %>%
        return
      })

names(Graphics) <- types
```

```{r Output, warning = FALSE}
# file.info
# file.info(DataFiles) %>% kable
# file.info(Memo.file) %>% kable

daily_summary %>% datatable
span_summary %>% datatable

Graphics

sessionInfo()
```

```{r eval = FALSE, echo = FALSE}
home.dir()
setwd("~/GitHub/BeeLabR/Environmental/MCH_grapher/")
rmarkdown::render("./MCH_grapher.Rmd", output_file = paste0("./", str_sub(Memo.file, end = -6), ".html"))
```