Spatial distribution mapper
========================================================
```{r eval = TRUE}
opts_chunk$set(eval = TRUE,
               error = FALSE,
               prompt = FALSE,
               message = FALSE,
               fig.hight = 10,
               fig.width = 12,
               warning =FALSE)
```

```{r eval = FALSE, echo = FALSE}
  filePath <- 
    readline("Enter the path to data file. ") 
  HomeGithub()
  knitr::knit2html("./environmental/PFDmap/PFDwithExcel.Rmd", output = paste0(filePath, "/", chamID, "_PFD.html"))
```

```{r}
Interpolate <-
  function(x){
    x_col <- zoo::na.approx(x)
    x_row <- t(zoo::na.approx(t(x)))
    x_col.row <- 0.5 * (x_col + x_row)
    x_col.row_col <- zoo::na.approx(x_col.row)
    x_col.row_col_row <- t(zoo::na.approx(t(x_col.row_col)))
    return(as.data.frame(x_col.row_col_row))
    }
```

```{r}

Colnum <-
  readline("Enter number of light color. ")  
chamID <-
  readline("Enter id of the chamber. ") 

PFD_summary <-
   lapply(1:Colnum, function(i){
  
  input <-
    dir(filePath, pattern = "xlsx", full.names = T) %>%
    read.xlsx(, sheetIndex = i)
  
  remarks <-
    input %>%
    select(1:2)
  
  data <-
    input %>%
    select(-(1:4))
    
  ColWithValues <-
    data %>%
    colwise(length2)(.) %>%
    unlist != 0
  
  ColIDs <-
    (0:(sum(ColWithValues)-1) * as.numeric(as.character(remarks[5, 2]))) %>%
    sprintf(fmt = "%02.0f") %>%
    paste0(., " cm")
  
  RowWithValues <-
    data %>% t %>% as.data.frame %>%
    colwise(length2)(.) %>%
    unlist != 0
  
  RowIDs <-
    ((sum(RowWithValues)-1):0 * as.numeric(as.character(remarks[5, 2]))) %>%
    sprintf(fmt = "%02.0f") %>%
    paste0(., " cm")
  
  forGraph <-
    data[RowWithValues, ColWithValues] %>%
    Interpolate %>%
    set_names(ColIDs[ColWithValues]) %>%
    mutate(Rows = RowIDs[RowWithValues]) %>%
    melt(id.vars = "Rows")
  
  forNums <-
    data[RowWithValues, ColWithValues] %>%
    set_names(ColIDs[ColWithValues]) %>%
    mutate(Rows = RowIDs[RowWithValues]) %>%
    melt(id.vars = "Rows") %>%
    set_names(c("Rows", "variable", "numeric"))
  
  PFDdata <-
    merge(forGraph, forNums, by = c("Rows", "variable"))
  
  PFDstat <-
    PFDdata$numeric %>%
    na.omit %>%
    adply(.margins = NULL, .fun = c("mean", "sd", "min", "max"))
  
  PFDmap <-
    PFDdata %>%
    set_names(c("Rows", "Cols", "value", "numeric")) %>%
    ggplot(aes(x = Cols, y = Rows, fill = value)) +
      geom_point(size = 30, shape = 22, alpha = 1) +
      scale_fill_gradient(low = "black", high = as.character(remarks[7, 2])) +
      geom_text(aes(x = Cols, y = Rows, label = numeric), color = "yellow", vjust = Inf) +
      theme_bw(20)
  
  data.frame(Meas_Start = remarks[1, 2],
             Meas_Fin = remarks[2, 2],
             Meas_Instrument = remarks[3, 2],
             Lamp_to_MeasSurface = remarks[4, 2],
             LightInfo = remarks[6, 2],
             LightSource = remarks[8, 2],
             PowerSupply = remarks[9, 2],
             Applied_Amp = remarks[10, 2],
             Applied_Volt = remarks[11, 2]
             ) %>%
  mutate(ColorCode = paste0(remarks[7, 2], "@", chamID)) %>%
  list(Info = ., list(data = PFDdata, stats = PFDstat, map = PFDmap))
  })

meas_infos <- 
  lapply(PFD_summary, "[[", 1) %>%
  rbind_all
```

`r kable(meas_infos)`
```{r result_info}
lapply(PFD_summary, "[[", 2) %>%
  set_names(meas_infos$ColorCode)
filePath %>% dir(pattern = "xlsx", full.names = T) %>% file.info %>% kable
sessionInfo()
```